node {

    withMaven(maven:'maven_3_5_4') {

        stage('Checkout') {
            git url: 'https://github.com/saurabh0010/sample-spring-microservices.git'
        }

        stage('Build') {
            sh 'mvn clean install'
        }

        stage('Image') {
            dir ('customer-service') {
                def app = docker.build "10.1.100.196:5000/customer-service"
                app.push()
            }
        }

        stage ('Run') {
            docker.image("10.1.100.196:5000/customer-service").run('-p 3333:3333 -h customer --name customer --link discovery --link account')
        }
    

    }

}
